### ISSUE TITLE
Misbehavior With Amino Types

### ISSUE THREAD

**Issue by DavideSegullo** [osmosis-labs/osmojs#12]
Hello, I'm using osmojs for [sinfonia-ui](https://github.com/bitsongofficial/sinfonia-ui), but I found two errors inside the AminoConverter:

1. The amino converter related to `/osmosis.lockup.MsgLockTokens` should produce as a return for the "toAmino" function an object with the following structure:
```typescript
{
  owner: string;
  duration: string;
  coins: Coin[];
}
```

Although, it returns an object with the following structure:
```typescript
{
    owner: string;
    duration: {
        seconds: string;
        nanos: number;
    };
    coins: {
        denom: string;
        amount: string;
    }[];
}
```

As it's possible to see, here the duration field is returned as an object with `seconds` and `nanos` attributes, instead of a single string.

That's how I implemented it on sinfonia:
https://github.com/bitsongofficial/sinfonia-ui/blob/9aaa13947b971d220ae64600704645faf2133efb/src/signing/amino-types.ts#L89

2. The amino type related to the message `/osmosis.lockup.MsgBeginUnlocking` seems to be wrong, it isn't `osmosis/lockup/begin-unlocking` as in [line 24](https://github.com/osmosis-labs/osmojs/blob/main/packages/osmojs/types/codegen/osmosis/lockup/tx.amino.d.ts#L24), since on osmosis it's defined such as `osmosis/lockup/begin-unlock-period-lock` as in [line 14](https://github.com/osmosis-labs/osmosis/blob/main/x/lockup/types/codec.go#L14). You could get another reference directly from the [osmosis frontend](https://github.com/osmosis-labs/osmosis-frontend/blob/master/packages/stores/src/account/types.ts#L67)

**Comment by pyramation** [comment]
thanks! great info. I'm also curious, how are you creating the `lockTokens` message? In many ways I'm happy to see this issue because I'm trying to get more information about it myself.

related: 
- https://github.com/osmosis-labs/telescope/issues/211
- https://github.com/osmosis-labs/telescope/issues/142

**Comment by DavideSegullo** [comment]
Ye, ofc that's how I create `lockTokens` message on [line 43](https://github.com/bitsongofficial/sinfonia-ui/blob/9aaa13947b971d220ae64600704645faf2133efb/src/signing/messages.ts#L43)

**Comment by pyramation** [comment]
ok so @DavideSegullo as an interface, you're essentially passing in durations as objects. This does make sense.

For context, we used strings because I had originally reverse engineered the code from osmosis-frontend which used strings. 

I'll be updating this after HackWasm! Thanks for the details :)

**Comment by pyramation** [comment]
Thanks! Will be able to sort this out soon, it's on my todo list!

**Comment by pyramation** [comment]
please try the new release candidate @JoseRFelix @DavideSegullo 

```
osmojs@15.1.0-rc.1
```

example here https://github.com/cosmology-tech/cosmology/blob/main/packages/cli/src/commands/lock.ts#L113-L116

```js

  const msg = lockTokens({
    owner: account.address,
    coins,
    duration: Duration.fromPartial({
      seconds: Long.fromString(duration),
      nanos: 0
    })
  });
  ```
