### ISSUE TITLE
'Long' only refers to a type, but is being used as a namespace here.

### ISSUE THREAD

**Issue by rishikhesh-cyD** [osmosis-labs/osmojs#14]
Facing this error for all use of Long inside this directory  
node_modules/cosmjs-types/tendermint/

example : 
<img width="518" alt="Screenshot 2022-10-11 at 1 35 47 PM" src="https://user-images.githubusercontent.com/107479292/195033809-c97c0f78-0282-408c-a270-7990b3206009.png">

**Comment by pyramation** [comment]
that is not this repository.
