### ISSUE TITLE
About broadcasting-messages

### ISSUE THREAD

**Issue by huzi0007** [osmosis-labs/osmojs#17]
links：https://github.com/osmosis-labs/osmojs#broadcasting-messages

I runned the code with the following errors：
![image](https://user-images.githubusercontent.com/37242575/195357933-c659c12c-e4a8-408c-8b9e-eb74904dd71a.png)

Need help，thanks！

**Comment by pyramation** [comment]
Thank you for catching this! the docs have been updated: https://github.com/osmosis-labs/osmojs#broadcasting-messages
