### ISSUE TITLE
export 'Long'.'UZERO' (imported as 'Long') was not found in 

### ISSUE THREAD

**Issue by cothi** [osmosis-labs/osmojs#19]
hello my tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,

// add esModuleInterop
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
```

my react App.tsx code
```tsx

import logo from './logo.svg';
import './App.css';
// this problem code
import { osmosis } from 'osmojs';


// start App
function App() {
  const { createRPCQueryClient } = osmosis.ClientFactory;
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}
export default App;
```

i refer https://github.com/osmosis-labs/osmojs/issues/18, then fix my tsconfig.json 
but, i see this error

![Screen Shot 2022-10-14 at 4 01 33 PM](https://user-images.githubusercontent.com/51845043/195783155-fc4c7492-0e44-4398-acc1-348b41a16c52.png)

how can i fix error ?

**Comment by pyramation** [comment]
hi @cothi thanks for providing this information.

The `Long` library is seemingly having issues. 

Because when we do `import Long from 'long'` we got an error. Now that we have `import * as Long from 'long'` we still have an error... One thought is maybe we need to install long types. I will look into this.

Another question — would you be willing to add me to your repo so I can take a deeper look and investigate in your environment? This could help us solve the issue with more visibility, let me know

**Comment by pyramation** [comment]
working on a PR to fix the TS stuff: https://github.com/osmosis-labs/osmojs/pull/20

**Comment by pyramation** [comment]
try `osmojs@0.33.0` and let me know, I switched it back to `import Long from 'long'` and other TS fixes/cleanup.

**Comment by cothi** [comment]
thanks, solved :)

**Comment by pyramation** [comment]
amazing! So happy to hear @cothi  :)
