### ISSUE TITLE
npm run error

### ISSUE THREAD

**Issue by thankst** [osmosis-labs/osmojs#23]
npm install osmojs         
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @cosmjs/stream@^0.29.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:

what should i do

**Comment by pyramation** [comment]
Are you using a npm registry of sorts? 

https://www.npmjs.com/package/@cosmjs/stream
<img width="447" alt="Screen Shot 2022-11-09 at 2 55 47 PM" src="https://user-images.githubusercontent.com/545047/200959817-9545ab5f-d001-4d33-bf51-879e63891f02.png">

**Comment by pyramation** [comment]
I would look at your network connection, ensure you're using the proper npm registry. Everything works, I also tested `yarn add osmojs` again and everything installs correctly.

**Comment by pyramation** [comment]
I also tested `npm install` which also works.
