### ISSUE TITLE
can't use import { getOfflineSignerAmino as getOfflineSigner } from 'cosmjs-utils' 

### ISSUE THREAD

**Issue by jb3134** [osmosis-labs/osmojs#24]
when i use import { getOfflineSignerAmino as getOfflineSigner } from 'cosmjs-utils' in https://github.com/osmosis-labs/osmojs/ example,  it always showed can't found cosmjs-utils
so where can i install the package ?? 
or how can i use getOfflineSigner method ????

**Comment by pyramation** [comment]
try installing by

```
yarn add cosmjs-utils
```

**Comment by pyramation** [comment]
you can make an issue here if it persists: https://github.com/cosmology-tech/cosmjs-utils

**Comment by jb3134** [comment]
thanks a lot .  i add it , and worked now.
i found that the READ.me and guild in OSMOSIS website had some wrong informations , so it's hard to get right result if you have no other help.
