### ISSUE TITLE
RewardsEstRequest missing height params

### ISSUE THREAD

**Issue by tandn37** [osmosis-labs/osmojs#29]
Currently in osmosisd, 
`osmosisd query incentives rewards-estimation`
allow to query by block height
`--height int        Use a specific height to query state at (this can error if the node is pruning state)`

But it's missing in RewardsEstRequest
`export interface RewardsEstRequest {
    owner: string;
    lockIds: Long[];
    endEpoch: Long;
}
`

**Comment by tandn37** [comment]
nvm

**Comment by Segfaultd** [comment]
Hey @tandn37 same issue here did you find a solution ?

**Comment by tandn37** [comment]
> Hey @tandn37 same issue here did you find a solution ?

sorry I dont remember about this at all, may be osmosisd version mismatch.
