### ISSUE TITLE
Jest raises Cannot read properties of undefined (reading 'sodium')

### ISSUE THREAD

**Issue by fboucquez** [osmosis-labs/osmojs#30]
Hi team, jest is raising this error when trying to use osmojs that depends on `libsodium-wrappers`

Minimal example:

```
import osmojs from 'osmojs'

test('osmojs', () => {
  console.log(osmojs)
})

```
Any hint on how to fix it?

**Comment by pyramation** [comment]
does it do this when you import a module, e.g. 

```ts
import { cosmos, osmosis } from 'osmojs'
```

can you also share your environment?
