### ISSUE TITLE
Geometric TWAP query bug

### ISSUE THREAD

**Issue by baoskee** [osmosis-labs/osmojs#48]
OSMO to ATOM pool geometric TWAP query is giving "52431954000000000". You need to shift this by 18 decimals to get the decimal value. This is surely a bug? 
```typescript
  return await client.osmosis.twap.v1beta1.geometricTwapToNow({
    poolId: Long.fromNumber(poolId),
    baseAsset,
    quoteAsset,

    startTime: startTime
      ? startTime
      : // Default is 60 minutes ago
        new Date(new Date().getTime() - 1000 * 60 * 60),
  });
  ```

**Comment by pyramation** [comment]
oh, we should use the `prototypes.typingsFormat.customTypes.useCosmosSDKDec` option from telescope, this is a bug on the backend, but telescope has a fix, will enable in next major version!

**Comment by pyramation** [comment]
should be fixed in v16!
