### ISSUE TITLE
typeof pool.id is a BigNumber instead of Long

### ISSUE THREAD

**Issue by humarkx** [osmosis-labs/osmojs#62]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@osmonauts/math@1.2.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@osmonauts/math/dist/pool.js b/node_modules/@osmonauts/math/dist/pool.js
index e000b0e..2920e20 100644
--- a/node_modules/@osmonauts/math/dist/pool.js
+++ b/node_modules/@osmonauts/math/dist/pool.js
@@ -188,7 +188,7 @@ const makePoolPairs = (pools, prices, liquidityLimit = 100000) => {
         if (!assetAinfo || !assetBinfo)
             return;
         return {
-            poolId: typeof pool.id === "string" ? pool.id : pool.id.low.toString(),
+            poolId: typeof pool.id === "string" ? pool.id : pool.id.toString(),
             poolAddress: pool.address,
             baseName: assetAinfo.display,
             baseSymbol: assetAinfo.symbol,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by pyramation** [comment]
we've moved to BigInt instead of long, if you want `Long`, you'll need to use telescope to build your own, or you can downgrade to an older version of osmojs

Long is a deprecated type
