### ISSUE TITLE
How to make a swap on osmosis

### ISSUE THREAD

**Issue by blavejr** [osmosis-labs/osmojs#7]
Hey guys, so I found this repo via cosmjs and cosmology and I have been trying for about 2 days now to make a swap on osmosis with no luck, I followed the examples and even read the core code trying to figure it out but I keep getting a 503 Service Unavailable, No server is available to handle this request error

Could you guys please maybe create an example with the simplest way to use this package to make a simple osmo to atom swap on osmosis?

**Comment by blavejr** [comment]
this is how I am trying to do it so far

`import {
  messages,
  getOsmoFee,
  lookupRoutesForTrade,
  prettyPool,
  PrettyPair,
  OsmosisApiClient,
  calculateAmountWithSlippage,
  getWalletFromMnemonic,
  getSigningOsmosisClient,
  makePoolPairs,
  makePoolsPretty,
  getPricesFromCoinGecko,
  symbolToOsmoDenom,
  baseUnitsToDisplayUnits,
  baseUnitsToDollarValue,
  getPrice,
  dollarValueToDenomUnits,
  getSwaps,
  signAndBroadcast,
} from "@cosmology/core";
import { coin } from "@cosmjs/amino";
import * as cosm from "./cosm";
import "dotenv/config";
import { rpcEndpoints, apiEndpoints } from "../static/enums";
// import { assets } from '@cosmology/cosmos-registry';
import { osmosis, GAS_VALUES } from "osmojs";
const {
  joinPool,
  exitPool,
  exitSwapExternAmountOut,
  exitSwapShareAmountIn,
  joinSwapExternAmountIn,
  joinSwapShareAmountOut,
  swapExactAmountIn,
  swapExactAmountOut,
} = osmosis.gamm.v1beta1.MessageComposer.withTypeUrl;

const testData = {
  cosmjsMnomic:
    "",
} as any;

(async () => {
  const wallet = await getWalletFromMnemonic({
    mnemonic: testData.cosmjsMnomic,
    token: "OSMO",
  });
  const client = await getSigningOsmosisClient({
    rpcEndpoint: rpcEndpoints.osmosis,
    signer: wallet,
  });
  const accounts = await wallet.getAccounts();
  const address = accounts[0].address;

    const api = new OsmosisApiClient({
      url: apiEndpoints.osmosisStakeSystems,
    });
    const lcdPools = await api.getPools();
    const prices = await getPricesFromCoinGecko();
    const prettyPools = makePoolsPretty(prices, lcdPools.pools);
    const pairs = makePoolPairs(prettyPools);

    const routes = lookupRoutesForTrade({
      // pools: prettyPools,
      trade: {
        sell: {
          denom: "uosmo",
          amount: "100",
          displayAmount: "",
          value: "10",
          symbol: "OSMO",
        },
        buy: {
          denom: 'ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2',
          amount: "20",
          displayAmount: "",
          value: "10",
          symbol: "ATOM",
        },
        beliefValue: "10",
      },
      pairs: pairs,
    }).map((tradeRoute) => {
      const { poolId, tokenOutDenom } = tradeRoute;
      return {
        poolId,
        tokenOutDenom,
      };
      // return tradeRoute;
    });

  // //   console.log(routes);

//   const fee = getOsmoFee("swapExactAmountIn");
const fee = GAS_VALUES.osmosis.swapExactAmountIn;

  const msg = swapExactAmountIn({
    sender: address,
    routes: [{
      poolId: routes[0].poolId,
      tokenOutDenom: routes[0].tokenOutDenom
  }],
    tokenIn: coin(100000, "uosmo"),
    tokenOutMinAmount: '9800'
  });

  // console.log(JSON.stringify(msg, null, 2));
//   let msgs = {
//     typeUrl: "/osmosis.gamm.v1beta1.MsgSwapExactAmountIn",
//     value: {
//       sender: "osmo1kurt7d8lre7udtq8dschstjjj400ms9f65kefx",
//       routes: [
//         {
//           poolId: "1",
//           tokenOutDenom:
//             "ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2",
//         },
//       ],
//       tokenIn: {
//         denom: "uosmo",
//         amount: "250000",
//       },
//       tokenOutMinAmount: "20000",
//     },
//   };

  const res = await signAndBroadcast({
    client: client,
    chainId: "osmosis-1",
    address,
    msg,
    fee: fee,
    memo: "Trade from osmosis-1",
  });

  console.log(res.code);
})();

//   const api = new OsmosisApiClient({
//     url: restEndpoint
//   });
//   const lcdPools = await api.getPools();
//   const pools = lcdPools.pools.map((pool) => prettyPool(pool));

//   const routes = lookupRoutesForTrade({
//     pools,
//     trade: {
//       sell: {
//         denom: tokenIn.denom,
//         amount: tokenInAmount
//       },
//       buy: {
//         denom: tokenOut.denom,
//         amount: tokenOutAmount
//       },
//       beliefValue: value
//     },
//     pairs
//   }).map((tradeRoute) => {
//     const {
//       poolId,
//       tokenOutDenom
//     } = tradeRoute;
//     return {
//       poolId,
//       tokenOutDenom
//     };
//   });

//   const tokenOutMinAmount = calculateAmountWithSlippage(
//     buy.amount,
//     slippage
//   );

//   const fee = getOsmoFee('swapExactAmountIn');
//   const msg = messages.swapExactAmountIn({
//     sender: address, // osmo address
//     routes, // TradeRoute
//     tokenIn: coin(amount, denom), // Coin
//     tokenOutMinAmount // number as string with no decimals
//   });
`

**Comment by pyramation** [comment]
a 503 error is a network error, you should try using another endpoint. This means that a node is down or having issues. 

If you have a specific error to report please make an issue, otherwise for support you can join the [discord here](https://discord.gg/6hy8KQ9aJY) where I am helping with issues dynamically

**Comment by blavejr** [comment]
`import {
  messages,
  getOsmoFee,
  lookupRoutesForTrade,
  prettyPool,
  PrettyPair,
  OsmosisApiClient,
  calculateAmountWithSlippage,
  getWalletFromMnemonic,
  getSigningOsmosisClient,
  makePoolPairs,
  makePoolsPretty,
  getPricesFromCoinGecko,
  symbolToOsmoDenom,
  baseUnitsToDisplayUnits,
  baseUnitsToDollarValue,
  getPrice,
  dollarValueToDenomUnits,
  getSwaps,
  signAndBroadcast,
  PriceHash,
} from "@cosmology/core";
import { coin } from "@cosmjs/amino";
import * as cosm from "./cosm";
import "dotenv/config";
import { rpcEndpoints, apiEndpoints } from "../static/enums";
// import { assets } from '@cosmology/cosmos-registry';
import { osmosis, GAS_VALUES } from "osmojs";
const {
  joinPool,
  exitPool,
  exitSwapExternAmountOut,
  exitSwapShareAmountIn,
  joinSwapExternAmountIn,
  joinSwapShareAmountOut,
  swapExactAmountIn,
  swapExactAmountOut,
} = osmosis.gamm.v1beta1.MessageComposer.withTypeUrl;

const testData = {
  cosmjsMnomic:
    "",
} as any;

const convertToDenomination = (value: number) => {
  // Here I am assuming that the value is in one millionth of a token
  return value * 1000000;
};

const getDollarValue = (prices: PriceHash, value: number, denom: string) => {
  const price = prices[denom];
  return value * price;
};

(async () => {
  const wallet = await getWalletFromMnemonic({
    mnemonic: testData.cosmjsMnomic,
    token: "OSMO",
  });
  const client = await getSigningOsmosisClient({
    rpcEndpoint: rpcEndpoints.osmosis,
    signer: wallet,
  });
  const accounts = await wallet.getAccounts();
  const address = accounts[0].address;

  const api = new OsmosisApiClient({
    url: apiEndpoints.osmosisStakeSystems,
  });
  const lcdPools = await api.getPools();
  const prices = await getPricesFromCoinGecko();
  const prettyPools = makePoolsPretty(prices, lcdPools.pools);
  const pairs = makePoolPairs(prettyPools);

  const routes = lookupRoutesForTrade({
    // pools: prettyPools,
    trade: {
      sell: {
        denom: "uosmo",
        amount: "100",
        displayAmount: "",
        value: "10",
        symbol: "OSMO",
      },
      buy: {
        denom:
          "ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2",
        amount: "20",
        displayAmount: "",
        value: "10",
        symbol: "ATOM",
      },
      beliefValue: "10",
    },
    pairs: pairs,
  }).map((tradeRoute) => {
    const { poolId, tokenOutDenom } = tradeRoute;
    return {
      poolId,
      tokenOutDenom,
    };
  });

  const fee = GAS_VALUES.osmosis.swapExactAmountIn;

  const msg = swapExactAmountIn({
    sender: address,
    routes: [
      {
        poolId: routes[0].poolId,
        tokenOutDenom: routes[0].tokenOutDenom,
      },
    ],
    tokenIn: coin(100000, "uosmo"),
    tokenOutMinAmount: "9800",
  });

  const res = await signAndBroadcast({
    client: client,
    chainId: "osmosis-1",
    address,
    msg,
    fee: fee,
    memo: "Trade from osmosis-1",
  });

  console.log(res.code);
})();`

**Comment by blavejr** [comment]
Alright thanks for the response. do you know where I can get other rpc providers?

**Comment by pyramation** [comment]
https://github.com/cosmos/chain-registry
which you can also use via npm https://github.com/cosmology-tech/chain-registry
