### ISSUE TITLE
'"osmojs"' has no exported member 'cosmos'

### ISSUE THREAD

**Issue by Jmarc369** [osmosis-labs/osmojs#80]
On trying to import cosmos from osmojs on v16.5.1 from 0.33.0, i encountered this error
to use this cosmos.bank.v1beta1.MessageComposer.withTypeUrl|

**Comment by shukr-acharya** [comment]
I also encountered similar kind of issue

 SyntaxError: The requested module '/node_modules/.vite/deps/osmojs.js?v=48110917' does not provide an export named 'cosmosAminoConverters'
